### ISSUE TITLE
Make subpages follow Feature Up format 

### ISSUE THREAD

**Issue by rebeccagoldman** [alexbaldwin/shareenso.com#2]
For Parents, Couples, Personal pages specifically. Currently they're categorized as posts under SiteLeaf, which will be a useful format for when we blog. But we need to add formatting for 'Page', and that should be the Feature Up format.

**Comment by alexbaldwin** [comment]
There already is a `page` layout, but pages don't specify a max-width or any of the `.prose` styles the same way the `posts` layout does. Specifying a layout doesn't mean that pages are categorized any differently.

The feature-up is a component that can be used from any layout, post, or page. I wouldn't recommend forcing a layout to be so rigid that it must include a component.
